// Generated by CoffeeScript 1.3.1
(function() {

  describe("BookmarkController", function() {
    return it("should work", function() {
      return new BookmarkController(jQuery);
    });
  });

}).call(this);
