// Generated by CoffeeScript 1.3.1
(function() {

  this.BookmarkCtrl = (function() {

    BookmarkCtrl.name = 'BookmarkCtrl';

    function BookmarkCtrl($scope) {
      this.$scope = $scope;
      this.$scope.bookmarks = [
        {
          id: 1,
          name: "one Bookmark",
          url: "http://some-url.de",
          read: false
        }
      ];
      this.$scope.editBoxStyle = "display: none;";
      this.$scope.onBookmarkReadClick = function(bookmark) {
        return bookmark.read = !bookmark.read;
      };
      this.$scope.getBookmarkReadClass = function(bookmark) {
        if (bookmark.read) {
          return "read";
        } else {
          return "unread";
        }
      };
    }

    return BookmarkCtrl;

  })();

}).call(this);
