// Generated by CoffeeScript 1.3.1
var Bookmark;

Bookmark = (function() {

  Bookmark.name = 'Bookmark';

  Bookmark.records = {};

  Bookmark.reset = function() {
    return this.records = {};
  };

  Bookmark.find = function(id) {
    return this.records[id] || (function() {
      throw "unknown record";
    })();
  };

  function Bookmark(id, name, url) {
    this.id = id;
    this.name = name;
    this.url = url;
    this.newRecord = true;
  }

  Bookmark.prototype.create = function() {
    this.newRecord = false;
    if (Bookmark.records[this.id]) {
      throw "record already exists";
    }
    return Bookmark.records[this.id] = this;
  };

  Bookmark.prototype.update = function() {
    if (!Bookmark.records[this.id]) {
      throw "record not yet exists";
    }
    return Bookmark.records[this.id] = this;
  };

  Bookmark.prototype.save = function() {
    if (this.newRecord) {
      return this.create();
    } else {
      return this.update();
    }
  };

  Bookmark.prototype.destroy = function() {
    if (!Bookmark.records[this.id]) {
      throw "record not yet exists";
    }
    return delete Bookmark.records[this.id];
  };

  return Bookmark;

})();
