// Generated by CoffeeScript 1.3.1
var BookmarkController;

BookmarkController = (function() {
  var $;

  BookmarkController.name = 'BookmarkController';

  $ = null;

  function BookmarkController(jQuery) {
    $ = jQuery;
    this.header = $('#header');
    this.editBox = $('#edit-box');
    this.bookmarks = $('#bookmarks');
    $.template("bookmark", $("#bookmarks .template").html());
    $("form", this.header).submit($.proxy(this.onHeaderFormSubmit, this));
    $("form", this.editBox).submit($.proxy(this.onEditBoxFormSubmit, this));
    $("input", this.header).focus();
  }

  BookmarkController.prototype.onHeaderFormSubmit = function(event) {
    var nameOrUrl;
    event.preventDefault();
    nameOrUrl = $(event.target.elements['search']).val();
    $(event.target.elements['search']).val("");
    return this.showAddItemForm(nameOrUrl);
  };

  BookmarkController.prototype.showAddItemForm = function(nameOrUrl) {
    var editForm;
    this.editBox.show();
    editForm = $('form', this.editBox);
    if (this.isUrl(nameOrUrl)) {
      $(editForm[0].elements['url']).val(nameOrUrl);
      return $(editForm[0].elements['name']).focus();
    } else {
      $(editForm[0].elements['url']).focus();
      return $(editForm[0].elements['name']).val(nameOrUrl);
    }
  };

  BookmarkController.prototype.onEditBoxFormSubmit = function(event) {
    var bookmark, editForm, nameField, urlField;
    event.preventDefault();
    editForm = $('form', this.editBox);
    urlField = $(editForm[0].elements['url']);
    nameField = $(editForm[0].elements['name']);
    if (!this.currentID) {
      this.currentID = 0;
    }
    Bookmark(bookmark = new Bookmark(this.currentID++, nameField.val(), urlField.val()));
    bookmark.save();
    $(editForm[0].elements['url']).val("");
    $(editForm[0].elements['name']).val("");
    return this.addBookmarkView(bookmark);
  };

  BookmarkController.prototype.addBookmarkView = function(bookmark) {
    var newElement;
    newElement = $.tmpl("bookmark", [
      {
        name: bookmark.name,
        url: bookmark.url
      }
    ]);
    newElement.prependTo(this.bookmarks);
    this.editBox.hide();
    return $("input", this.header).focus();
  };

  BookmarkController.prototype.isUrl = function(value) {
    return value.indexOf("http://") === 0;
  };

  return BookmarkController;

})();
